### ISSUE TITLE
For what reason you was made DB filling as a service?

### ISSUE THREAD

**Issue by a-a-k** [robinvanderknaap/authorization-server-openiddict#2]
I can't figure that out, why didn't you fill DB in `Startup.cs` directly while configuring other stuff? Why `IHostedService`?

**Comment by robinvanderknaap** [comment]
At the time It seemed like an easy way to configure the clients. I think I saw the author of OpenIddict do it like this in one of his examples. How would you approach this? Do you have an example?

**Comment by a-a-k** [comment]
Actually, I have no example for OpenIddict, but there are a lot of samples for a regular DB filling. I may suppose how it might look like but I don't know what entities I need to initiate with data, that's it.
